runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: Proyek/proyek.html
  upload: Proyek/proyek.html

- url: /(.*)
  static_files: Proyek/\1
  upload: Proyek/(.*)